default message

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,22 +1,33 @@
 #!/usr/bin/env bash
-#Install nginx on your web-01
-# Configure nginx to listen on port 80 and serve "Hello World!" on root request
-# Restart nginx
+#install ngix and have a file that returns the string "Hello World  inside
 
-apt-get update
-apt-get -y install nginx
-echo "server {
-        listen 80 default_server;
-        listen [::]:80 default_server;
-
-        root /var/www/html;
-        index index.html index.htm;
-
-        server_name _;
-
-        location / {
-                try_files \$uri \$uri/ =404;
-                echo 'Hello World!';
+sudo apt-get update -y && \
+sudo apt-get install -y nginx
+if [ $? -eq 0 ]
+then
+    echo -e \
+"http {
+    root /var/www/school;
+    index index.html;
+    server {
+        listen 80;
+        location \ {
         }
-}" > /etc/nginx/sites-available/default
-service nginx restart
+    }
+}
+events {
+}" > /etc/nginx/nginx.conf
+    mkdir -p /var/www/school
+    echo "Hello World!" > \
+	/var/www/school/index.html
+    service nginx start
+    if [ $? -ne 0 ]
+    then
+	"Problem starting nginx"
+	exit 1
+    fi
+else
+    echo "Could not install nginx"
+    exit 1
+fi
+exit 0
